Add default bazelrc configuration, and a bunch of useful configs.
Unfortunately I can't try building portage packages since it's failing at  head, but I can verify that it fails the same way with this patch, and that non-portage packages build fine.

Change-Id: I447684604e0dfdf97e468a876416a4f64db0b3e9
Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/cros-bazel/+/1621435
Reviewed-by: Tim Bain <tbain@google.com>

diff --git a/workspace_root/tools/bazel b/workspace_root/tools/bazel
--- a/workspace_root/tools/bazel
+++ b/workspace_root/tools/bazel
@@ -10,11 +10,19 @@ if GO="$(command -v go)"; then
     PATH="${PATH}:$("$GO" env GOPATH)/bin"
 fi
 
-if BAZELISK="$(command -v bazelisk)"; then
-    exec "${BAZELISK}" "$@"
+# Allow users to create a bazelrc file shared between all chromiumos checkouts.
+# ~/.bazelrc is also shared between all chromiumos checkouts, but it also has
+# non-chromiumos stuff.
+ARGS=()
+if [ -e "$HOME/.chromiumos.bazelrc" ]; then
+  ARGS+=("--bazelrc=$HOME/.chromiumos.bazelrc")
 fi
 
-echo "Bazlisk was not found. Please install using the following command:" 1>&2
+if BAZELISK="$(command -v bazelisk)"; then
+    exec "${BAZELISK}" "${ARGS[@]}" "$@"
+fi
+
+echo "Bazelisk was not found. Please install using the following command:" 1>&2
 echo "> go install github.com/bazelbuild/bazelisk@latest" 1>&2
 
 exit 1
