Remove link_files.py, minimize Alchemy's tools/bazel launcher
link_files.py is now obsolete by the Bazel launcher (in CL:4718365).
The logic in tools/bazel for Alchemy can now be significantly
minimized as well, as we don't have to worry about finding and running
with Bazelisk.

BUG=b:253268519
TEST=BOARD=amd64-generic bazel --project alchemy query '@portage//sys-apps/attr'

Cq-Depend: chromium:4718365
Change-Id: I2fdc7dc7fea42c8713b6df3e5050fef86ee5495d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/bazel/+/4718047
Reviewed-by: Ryo Hashimoto <hashimoto@chromium.org>
Tested-by: Jack Rosenthal <jrosenth@chromium.org>
Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-by: Shuhei Takahashi <nya@chromium.org>

diff --git a/workspace_root/alchemy/tools/bazel b/workspace_root/alchemy/tools/bazel
--- a/workspace_root/alchemy/tools/bazel
+++ b/workspace_root/alchemy/tools/bazel
@@ -5,10 +5,10 @@
 
 set -eu -o pipefail
 
-# Add users go path before trying
-if GO="$(command -v go)"; then
-    # Add /bin to every entry in gopath.
-    PATH="${PATH}:$("${GO}" env GOPATH | sed 's/:/\/bin:/g')/bin"
+# We expect BAZEL_REAL to be set by Bazel.
+if [[ -z "${BAZEL_REAL:=}" ]]; then
+  echo "ERROR: BAZEL_REAL must be set." >&2
+  exit 1
 fi
 
 # Allow users to create a bazelrc file shared between all chromiumos checkouts.
@@ -19,35 +19,21 @@ if [ -e "${HOME}/.chromiumos.bazelrc" ]; then
   ARGS+=("--bazelrc=${HOME}/.chromiumos.bazelrc")
 fi
 
-if BAZELISK="$(command -v bazelisk)"; then
+while [[ "$#" -gt 1 ]]; do
+  if [[ "$1" == --* ]]; then
+    ARGS+=("$1")
+    shift
+  else
+    break
+  fi
+done
 
-    while [[ "$#" -gt 1 ]]; do
-        if [[ "$1" == --* ]]; then
-            ARGS+=("$1")
-            shift
-        else
-            break
-        fi
-    done
-
-    # Used to force the alchemist_digest repo rule to re-run every invocation.
-    if [[ "$#" -gt 1 ]]; then
-        ARGS+=("$1")
-        shift
-        CACHE_BUST_DATE="${CACHE_BUST_DATE:-$(date --iso-8601=ns)}"
-        ARGS+=("--repo_env=_CACHE_BUST_DATE=${CACHE_BUST_DATE}")
-    fi
-
-    # Create necessary symbolic links.
-    "$(dirname "${BASH_SOURCE[0]}")/../../../link_files.py"
-
-    # We don't want bazelisk to call us again.
-    export BAZELISK_SKIP_WRAPPER=true
-
-    exec "${BAZELISK}" "${ARGS[@]}" "$@"
+# Used to force the alchemist_digest repo rule to re-run every invocation.
+if [[ "$#" -gt 1 ]]; then
+  ARGS+=("$1")
+  shift
+  CACHE_BUST_DATE="${CACHE_BUST_DATE:-$(date --iso-8601=ns)}"
+  ARGS+=("--repo_env=_CACHE_BUST_DATE=${CACHE_BUST_DATE}")
 fi
 
-echo "Bazelisk was not found. Please install using the following command:" 1>&2
-echo "> go install github.com/bazelbuild/bazelisk@latest" 1>&2
-
-exit 1
+exec "${BAZEL_REAL}" "${ARGS[@]}" "$@"
